---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-operator-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: capi-operator
  namespace: capi-operator-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/cluster-api-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capi-operator
  namespace: capi-operator-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 30m
  chart:
    spec:
      chart: cluster-api-operator
      version: "0.7.x"
      sourceRef:
        kind: HelmRepository
        name: capi-operator
        namespace: capi-operator-system
      interval: 12h
