---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  version: v1.4.3
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
  name: sidero
  namespace: capi-system
spec:
  version: v0.6.1
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: BootstrapProvider
metadata:
  name: talos
  namespace: capi-system
spec:
  version: v0.6.2
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: ControlPlaneProvider
metadata:
  name: talos
  namespace: capi-system
spec:
  version: v0.5.3